build:
  image: bjodah/bjodahimg16:v1.2
  commands:
    - (cd .binaries; python3 -m pip install --ignore-installed -f . sympy-03d75d6.tar.gz)
    - (cd .binaries; python2 -m pip install --ignore-installed -f . sympy-03d75d6.tar.gz rst2pdf-0.93.tar.gz)
    - cd ./application;
    - make
    - jupyter nbconvert --to=html --debug --ExecutePreprocessor.enabled=True --ExecutePreprocessor.timeout=300 *.ipynb
    - python3 -m pytest
    - cd -
    - bash -ce '! grep "System Message:" application/*.html'
    - cd ./report;
    - git clone git://github.com/bjodah/sympy.git --branch codegen-ast-more-nodes
    - PYTHONPATH=$(pwd)/sympy python3 -m doctest -f report.rst
    - make
    - cd -
    - bash -ce '! grep "System Message:" report/*.html'
    - mkdir -p deploy/$CI_BRANCH
    - cp application/proposal.rst application/*.html application/*.pdf report/*.html report/*.pdf deploy/$CI_BRANCH

deploy:

  rsync:
    host: hera.physchem.kth.se
    port: 22
    user: gsoc2017-bjodah
    source: deploy/
    target: ~/public_html
    recursive: true
    delete: false
